personal_portfolio/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.detail, name='detail'),
    path ('p', views.pretty)
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include



urlpatterns = [
    path('admin/', admin.site.urls),
    #path ('', views.home),
    #path ('home', views.home),
    #path ('p', views.pretty),
    path('blog/', include('blog.urls')),
    path('', include ('portfolio.urls')),
    path('shows/', include('shows.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/portfolio/urls.py
from django.urls import path
from . import views

app_name = 'folio'
urlpatterns = [
    path('', views.home, name="home"),
     path('home', views.home, name="home")
]

personal_portfolio/shows/urls.py
from django.urls import path
from . import views

app_name = 'shows'
urlpatterns = [
    path('', views.all_shows, name="all_shows")
    ]

personal_portfolio/blog/models.py
from django.db import models

# Create your models here.




class BlogPost(models.Model):
    post_date= models.DateField()
    title= models.TextField()
    post_text = models.CharField(max_length=1000)
    

    def __str__(self):
        return self.title

personal_portfolio/portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title= models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField (upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio/shows/models.py
from django.db import models

# Create your models here.

personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse  # added
from .models import BlogPost #added 


# Create your views here.


def home(request):  # function added
    return HttpResponse("blogs home page")

def all_blogs (request): #function added
    posts = BlogPost.objects.order_by('-post_date')
    print (type(posts))
    return render (request, 'blog/all_blogs.html', {'posts':posts})

def detail (request, blog_id):
    blog=get_object_or_404(BlogPost, pk=blog_id)
    return render (request, 'blog/detail.html', {'blog':blog})

def pretty (request):
    return render (request, 'blog/base.html')

     

personal_portfolio/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse  # added
from .models import Project


# Create your views here.

def home2(request):  # function added
    return HttpResponse("home page")



def home (request):
    projects=Project.objects.all()
    return render (request, 'folio/home.html', {'projects':projects})

def pretty (request):
    return render (request, 'folio/base.html')

personal_portfolio/shows/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse  # added

# from .models import BlogPost #added


'''
# Create your views here.
def all_blogs (request): #function added
    posts = BlogPost.objects.order_by('-post_date')
    print (type(posts))
    return render (request, 'blog/all_blogs.html', {'posts':posts})

'''


def all_shows(request):  # function added
    print ('all_shows')
    return HttpResponse("live shows")

personal_portfolio/blog/templates/blog/all_blogs.html
{% extends "folio/base.html" %}

{% load static %}

{% block content %}


Hello Blogs
<BR>

    Blog Entries 
<br>
Mike has written {{posts.count}} blog{{posts.count| pluralize}}
<br>
{% for post in posts %}
    <br>
    <Br>
        <br>
    {{ post.post_date | date:'M d Y'| upper }}
    <br>
  <a  href ="{% url 'blog:detail' post.id  %}">
      {{post.title}}  </a>
<Br>
 {{post.post_text | striptags|  truncatechars:100}}

{% endfor %}
{% endblock %}

personal_portfolio/blog/templates/blog/detail.html
{% extends "folio/base.html" %}

{% load static %}

{% block content %}

{{blog}}

<h1>
    {{blog.title}}
</h1>
<h2>
    --{{blog.post_date | date:'F jS Y'}}---
</h2>

{{blog.post_text | safe}}


{% endblock %}

personal_portfolio/portfolio/templates/folio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "folio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "folio/Logo.png" %}">

  <title>Michael Rubinstein</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="home">
        <img src="{% static "folio/Logo.png" %}"
         width="30" height="30" class="d-inline-block align-top" 
         alt="Nick's Logo">
        <span>Michael Rubinstein</span>
      </a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      
      </button>
      
      
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">

         


          <li class="nav-item">
            <a class="nav-link" 
            href="{% url 'blog:all_blogs' %}">
            blog
          </a>
          </li>

      
          
          <li class="nav-item">
            <a class="nav-link" 
            href="{% url 'folio:home' %}">
            home
          </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% static "folio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/nick-walter/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

personal_portfolio/portfolio/templates/folio/home.html
{% extends "folio/base.html" %}
{% load static %}
{% block content %}



    <Br>
    
        

     <img src=" {% static 'folio/card.jpeg' %} " height="500" width="300" alt="photo goes here"> 

     <a href = " {% static 'folio/resume.pdf' %} ">resume</a>

    <Br>
<a href = /blog>All Blogs</a>
    <br>
{% for project in projects  %}
<br>
<br>
<br>
***********************
<br>
{{project.title}}
<br>
{{project.description}}
<Br>
{{project.image.url}}
<Br>
    <img src="{{project.image.url}}" height="700" width="1050" >
    <Br>
        {{project.url}}
    <br>
    <a href= {{project.url}}>Link</a>

{%endfor%}

{% endblock %}